// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bohilarmhqtgqkanovkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvaGlsYXJtaHF0Z3FrYW5vdmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDU2NTMsImV4cCI6MjA2NDg4MTY1M30.c1pO14mIS2odHdNjWLm2xBJ_Pnb3GpdufSu9YenkrF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);